[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[config]
indent = "\t"
line_length = 115

[hooks.yapf]
priority = 30

[hooks.isort]
priority = 50

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort.kwargs]
indent = "\t\t"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = [
    "aenum",
    "autodocsumm",
    "backports_entry_points_selectable",
    "biopython",
    "cftime",
    "coincidence",
    "coverage",
    "coverage_pyver_pragma",
    "coveralls",
    "deprecation",
    "domdf_python_tools",
    "enum_tools",
    "extras_require",
    "github",
    "jupyter",
    "matplotlib",
    "nbconvert",
    "nbsphinx",
    "netcdf4",
    "numpy",
    "openpyxl",
    "pandas",
    "pillow",
    "pymzml",
    "pypandoc",
    "pytest",
    "pytest_cov",
    "pytest_mpl",
    "pytest_randomly",
    "pytest_regressions",
    "pytest_rerunfailures",
    "pytest_timeout",
    "pytz",
    "requests",
    "scipy",
    "sdjson",
    "sphinx",
    "sphinx_autodoc_typehints",
    "sphinx_notfound_page",
    "sphinx_prompt",
    "sphinx_rtd_theme",
    "sphinx_tabs",
    "sphinxcontrib_httpdomain",
    "sphinxemoji",
    "typing_extensions",
]
known_first_party = "pyms"
